name: table_sticky_headers_example
description: Two-dimension table with both sticky headers. You may scroll left \ right and top \ bottom. Sticky headers always stay visible. Legend cell (top left) always visible too.
homepage: https://github.com/AlexBacich/sticky-headers-table

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.0.3
  flutter:
    sdk: flutter
  table_sticky_headers:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

